from PIL import Image, ImageDraw, ImageFont

lyrics = 'DJ QUIK Lyrics[Intro]\nIf it don\'t make dollars, it don\'t make sense\nSo don\'t kill game, let the pimpin\'—\n\n[Verse 1]\nI ain\'t never quittin\' on my homies from the set\nRather die a legend than be livin\' with regrets\nGranny up in Heaven, know she watch a nigga back\nG Class, flyin\' down\' Orizaba Ave\nI know that you love me but you gotta give me space\nMoney hungry women do whatever for a taste\nAll my people \
in the hood, what it\'s finna take\nTo have everybody livin\' good? I don\'t wanna wait\nIn a minute, I\'ma bust a juug, I\'ma make a play\nHit the homie up and hit a lick, run in where you stay\nAll the pressure \
I be dealin\' with, still ain\'t ever change\nI\'m about the money, I ain\'t fuckin\' with the fame\n[Chorus]\nDJ Quik (Get paid, get paid, young nigga, get paid)\nIf it don\'t make dollars, then it don\'t make sense\n(Get paid, young nigga, get paid, get paid, young nigga, get paid)\nDJ Quik (Get paid, get paid, young nigga, get paid)\nIf it don\'t make dollars, then it don\'t make sense\n(Get paid, young nigga, get paid, get paid, young nigga, get paid, get paid)\n\n[Verse 2]\nYou should see the limit on my Amex\nOne phone call and it\'s niggas at your address\nI\'m gon\' ball \'til I\'m sittin\' in the grave\nFuck all y\'all, bet Ramona get the last laugh\nClose your mouth when you talkin\' to a killer, bitch\nThey say I murder cuh, I say, "I\'m innocent"\nThis ain\'t suburbia, these niggas ignorant\nI always get my man, I only miss my bitch\nYeah, hit me up if you wish\nI\'m in the studio, couple guns, couple Crips\nTryna make a hunnid Ms, what\'s a couple bands?\nKeep it comin\' in, keep it comin\' in\n\n[Chorus]\nDJ Quik (Yeah, get paid, get paid, young nigga, get paid)\nIf it don\'t make dollars, then it don\'t make sense\n(Get paid, young nigga, get paid, get paid, young nigga, get paid)\nDJ Quik (Get paid, get paid, young nigga, get paid)\nIf it don\'t make dollars, then it don\'t make sense\n(Get paid, young nigga, get paid, get paid, young nigga, get paid, get paid)\nYou might also like[Outro]\n(Get paid, yeah, get paid, young nigga, get paid\nGet paid, young nigga, get paid, get paid, young nigga, get paid)\nNigga that you know that\'s been down for years\nI\'ve clowned for years, and y\'all could never fade my peers\nOne, two, three, four, five—3Embed'

img = Image.open('assets/test.jpeg')
img_draw = ImageDraw.Draw(img)
font = ImageFont.truetype("assets/fonts/Apple/AppleGaramond.ttf", 14)
img_draw.text((0, 0), lyrics, align="left", font=font)
img.show()